# Generated by Django 6.0.6 on 2026-06-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_onboarding_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
