# Generated by Django 6.0.6 on 2026-06-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Product',
        ),
    ]
