# Generated by Django 6.0.6 on 2026-06-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
