# Generated by Django 6.0.6 on 2026-06-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='digital', max_length=10),
        ),
    ]
